version: "3.8"

services:
  zomboid-server:
    image: renegademaster/zomboid-dedicated-server:2.5.0
    environment:
      - ADMIN_USERNAME=${PZ_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${PZ_ADMIN_PASSWORD}
      - "AUTOSAVE_INTERVAL=5"
      - "BIND_IP=0.0.0.0"
      - "GAME_PORT=8766"
      - "GAME_VERSION=public"
      - "MAX_PLAYERS=10"
      - "MAX_RAM=8192m"
      - "MOD_NAMES="
      - "MOD_WORKSHOP_IDS="
      - "NO_CHOWN_CONFIG_DIR=false"
      - "NO_CHOWN_GAME_DIR=false"
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "QUERY_PORT=16261"
      - "SERVER_NAME=YoulZoid"
      - SERVER_PASSWORD=${PZ_SERVER_PASSWORD}
      - "STEAM_VAC=true"
      - "USE_STEAM=true"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
#      - target: 27015
#        published: 27015
#        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
      - ./ZomboidCustomConfig:/home/steam/ZomboidCustomConfig/
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid.ini
#        target: /home/steam/Zomboid/Server/YoulZoid.ini
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_SandboxVars.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_SandboxVars.lua
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_spawnpoints.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_spawnpoints.lua
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_spawnregions.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_spawnregions.lua
