#
#  Project Zomboid Dedicated Server using SteamCMD Docker Image.
#  Copyright (C) 2021-2022 Renegade-Master [renegade.master.dev@protonmail.com]
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3.8"

services:
  zomboid-server:
    image: renegademaster/zomboid-dedicated-server
    user: "1000:1000"
    environment:
      - "ADMIN_PASSWORD=barlito"
      - "ADMIN_USERNAME=barlito"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "GAME_PORT=8766"
      - "GAME_VERSION=public"
      - "MAX_PLAYERS=5"
      - "MAX_RAM=4096m"
      - "MOD_NAMES=59meteor;ECTO1;67commando;74amgeneralM151A2;78amgeneralM35A2;78amgeneralM49A2C;tsarslib;78amgeneralM50A3;RS_WaterCistern;80kz1000;amclub;82oshkoshM911;83amgeneralM923;84merc;85merc;86oshkoshP19A;87cruiser;88golfMk2;88jettaMk2;89def110;89def90;90niva;91range;92amgeneralM998;1904952813;LitSortOGSN;LitSortOGSN_readOnePage;LitSortOGSN_chocolate;LitSortOGSN_rice;LitSortOGSN_gold;LitSortOGSN_diamond;AquatsarYachtClub;Arsenal(26)GunFighter;modoptions;autotsartrailers;ATA_Bus;BecomeDesensitized;BedfordFalls;Brita_2;Brita;CrashedCarsMod;FRUsedCarsNLF;FRUsedCarsNRN;FRUsedCars;FRUsedCarsFT;GunSuicide;P4HasBeenRead;KillCount;ModManager;ModManagerServer;ModTemplate;MoreDescriptionForTraits4166;ToadTraits;ToadTraitsDisablePrepared;ToadTraitsDisableSpec;ProgressiveCharacterMod;RV_Interior;RV_Interior_MP;RavenCreek;RS_WaterCistern_FR_Overwrite;RS_WaterCistern_KI5_Addon;VVehicleEnhancer;NamedSkillVHSTapes;AxeOverhaul;FixedCraftableAxes;TheStar;TowingCar;HTowTruck;fuelsideindicator;ProfessionFrameworkB41Patch;betterLockpicking;ATA_Jeep;ReLght"
      - "MOD_WORKSHOP_IDS=2772575623;2478247379;2785549133;2799152995;2392709985;2719592131;2818847163;2778576730;2618213077;2811383142;2805630347;2469388752;2566953935;2489148104;2516123638;2522173579;2441990998;2443275640;2422681177;2409333430;2642541073;1904952813;2071347174;2392987599;2297098490;2169435993;2282429356;2592358528;2627877543;522891356;2460154811;2200148440;1539281445;1510950729;2402057349;2544353492;2553809727;2694448564;2725216703;2685168362;1299328280;2659093221;2822286426;2196102849;2788428718;2732294885;2679338204;2684955236;2619072426;2241990680;2292487242;2616986064;2216760107;2368058459;2636100523;2780594299"
      - "NO_CHOWN_CONFIG_DIR=false"
      - "NO_CHOWN_GAME_DIR=false"
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "QUERY_PORT=16261"
      - "SERVER_NAME=YoulZoid"
      - "SERVER_PASSWORD=veliveli"
      - "STEAM_VAC=true"
      - "USE_STEAM=true"
      - "MAX_RAM=8192m"
    ports:
      - target: 8766
        published: 8766
        protocol: udp
      - target: 16261
        published: 16261
        protocol: udp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
      - type: bind
        source: ./ZomboidCustomConfig/YoulZoid.ini
        target: /home/steam/Zomboid/Server/YoulZoid.ini
      - type: bind
        source: ./ZomboidCustomConfig/YoulZoid_SandboxVars.lua
        target: /home/steam/Zomboid/Server/YoulZoid_SandboxVars.lua
      - type: bind
        source: ./ZomboidCustomConfig/YoulZoid_spawnregions.lua
        target: /home/steam/Zomboid/Server/YoulZoid_spawnregions.lua
