version: "3.8"

services:
  zomboid-server:
    image: renegademaster/zomboid-dedicated-server:2.5.0
    environment:
      - ADMIN_USERNAME=${PZ_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${PZ_ADMIN_PASSWORD}
      - SERVER_PASSWORD=${PZ_SERVER_PASSWORD}
      - "SERVER_NAME=YoulZoid"
      - "AUTOSAVE_INTERVAL=5"
      - "BIND_IP=0.0.0.0"
      - "GAME_VERSION=public"
      - "MAX_PLAYERS=10"
      - "MAX_RAM=8192m"
      - "PAUSE_ON_EMPTY=true"
      - "QUERY_PORT=16261"
      - "STEAM_VAC=true"
      - "DEFAULT_PORT=16261"
      - "UDP_PORT=16262"
      - "USE_STEAM=true"
      - "MAP_NAMES=Muldraugh, KY;BedfordFalls;Blackwood;Grapeseed;vehicle_interior;RavenCreek;MotoriousExpandedSpawnZones"
      - "MOD_NAMES=78amgeneralM35A2;78amgeneralM49A2C;78amgeneralM62;78amgeneralM50A3;83amgeneralM923;82porsche911;damnlib;89def110;89def90;1969FordMustangBoss429;LitSortOGSN;LitSortOGSN_readOnePage;LitSortOGSN_rice;VISIBLE_BACKPACK_BACKGROUND;BecomeDesensitized;BedfordFalls;BetterBatteries;BetterSortCC;Blackwood;BB_CommonSense;CrashedCarsMod;FixedCraftableAxes;fuelsideindicator;BION_DropBags;Grapeseed;GRGV;improvedbuildmenu41-2;improvedhairmenu;qdx_item_condition;KillCount;MapLegendUI;mapmodmanager;ModManager;ModManagerServer;NamedSkillVHSTapes;OutTheWindow;BION_PlainMoodles;RV_Interior_MP;RV_Interior_Vanilla;RainCleansBlood;RainWash;RavenCreek;ReLght;REORDER_CONTAINERS;SpeedReading;P4TidyUpMeister;VVehicleEnhancer;fhqExpVehSpawn"
      - "MOD_WORKSHOP_IDS=2799152995;2811383142;3379334330;3171167894;2441990998;2443275640;2273010892;2071347174;2808679062;2627877543;522891356;2856174410;2313387159;2536865912;2875848298;1539281445;2684955236;2616986064;3018929461;2463499011;3078291265;1969456967;2732662310;2852309899;2553809727;2710167561;3360392628;2694448564;2725216703;2732294885;2659216714;3008416736;2822286426;2956146279;2657661246;2196102849;2780594299;2901962885;1406668075;2769706949;2788428718;2793164190"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
#      - target: 27015
#        published: 27015
#        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
      - ./ZomboidCustomConfig:/home/steam/ZomboidCustomConfig/
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid.ini
#        target: /home/steam/Zomboid/Server/YoulZoid.ini
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_SandboxVars.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_SandboxVars.lua
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_spawnpoints.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_spawnpoints.lua
#      - type: bind
#        source: ./ZomboidCustomConfig/YoulZoid_spawnregions.lua
#        target: /home/steam/Zomboid/Server/YoulZoid_spawnregions.lua
